# Generated by Django 4.2.7 on 2024-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
    ]
