# Generated by Django 4.2.7 on 2024-08-04 02:43

import apis.models
import autoslug.fields
import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of Institution",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "brand_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Institution Logo",
                        null=True,
                        upload_to="institution_logos/",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True,
                        help_text="institutions unique subdomain namespace",
                        null=True,
                        populate_from="name",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("individual", "individual"),
                            ("school", "school"),
                            ("government", "government"),
                        ],
                        default="individual",
                        validators=[apis.models.Institution.type_validator],
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "default_language",
                    models.CharField(
                        blank=True, default="english", max_length=255, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="CAD", max_length=16, null=True
                    ),
                ),
                (
                    "brand_primary_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="#FF0000",
                        help_text="Primary color",
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "brand_secondary_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="#FFFF00",
                        help_text="Secondary color for buttons",
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "brand_tertiary_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="#FFFFFF",
                        help_text="backup color",
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Lesson", max_length=255, null=True
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LessonPlaylist",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.lesson"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True,
                        help_text="Program unique slug",
                        null=True,
                        populate_from="title",
                    ),
                ),
                ("short_description", models.TextField(blank=True, null=True)),
                ("long_description", models.TextField(blank=True, null=True)),
                ("cost", models.IntegerField()),
                ("public", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="programs/")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated length of weeks to complete program.",
                        null=True,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apis.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "maximum_students",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apis.institution",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apis.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "STUDENT"),
                            ("INSTRUCTOR", "INSTRUCTOR"),
                            ("ADMIN", "ADMIN"),
                        ],
                        default="STUDENT",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="default.jpeg", null=True, upload_to=""
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "lessons",
                    models.ManyToManyField(
                        through="apis.LessonPlaylist", to="apis.lesson"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "meeting_link",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("recorded_video", models.URLField(blank=True, null=True)),
                ("transcript", models.URLField(blank=True, null=True)),
                (
                    "is_recurring",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="apis.lesson",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lessonplaylist",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apis.playlist"
            ),
        ),
        migrations.CreateModel(
            name="LessonNote",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apis.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LessonAttendance",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("join_time", models.DateTimeField(blank=True, null=True)),
                ("leave_time", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.lesson"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="apis.program",
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apis.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Lesson Assignment", max_length=255),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("attachment", models.URLField(blank=True, null=True)),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.lesson"
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "title"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("payment_info", models.CharField(default="Trial", max_length=16)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="apis.program",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="apis.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("student", "session")},
            },
        ),
        migrations.CreateModel(
            name="InstructorEnrollment",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_enrolled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.program"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_enrollments",
                        to="apis.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("instructor", "session")},
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("other", "Other"),
                        ],
                        default="active",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("attachment", models.URLField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("late", "Late"),
                        ],
                        default="submitted",
                        max_length=10,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apis.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("student", "assignment")},
            },
        ),
    ]
