# Generated by Django 4.2.7 on 2024-08-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_open',
        ),
    ]
