# Generated by Django 4.2.7 on 2024-08-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_session_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
