# Generated by Django 4.2.7 on 2024-02-17 23:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_alter_submission_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="submissions",
        ),
        migrations.RemoveField(
            model_name="course",
            name="instructors",
        ),
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="owner",
        ),
        migrations.AddField(
            model_name="classroom",
            name="namespace",
            field=autoslug.fields.AutoSlugField(
                editable=True, null=True, populate_from="title"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="namespace",
            field=autoslug.fields.AutoSlugField(
                editable=True, null=True, populate_from="title"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="apis.assignment",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis.profile",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name="StudentSession",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apis.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apis.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="session",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis.course",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="instructors",
            field=models.ManyToManyField(
                related_name="Courses_teaching", to="apis.profile"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="students",
            field=models.ManyToManyField(
                related_name="Courses_registered",
                through="apis.StudentSession",
                to="apis.profile",
            ),
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("courses", models.ManyToManyField(to="apis.course")),
                (
                    "instructors",
                    models.ManyToManyField(
                        related_name="Cohorts_teaching", to="apis.profile"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="Cohorts_registered", to="apis.profile"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
