# Generated by Django 4.2.7 on 2024-02-24 07:52

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_session_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='namespace',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='namespace',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructors',
            field=models.ManyToManyField(related_name='sessions_teaching', to='apis.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(related_name='sessions_registered', through='apis.StudentSession', to='apis.profile'),
        ),
    ]
