# Generated by Django 4.2.7 on 2024-02-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_assignment_due_date_alter_classroom_namespace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='roles',
            new_name='role',
        ),
    ]
