# Generated by Django 4.2.7 on 2024-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_roles_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(related_name='cohorts_teaching', to='apis.profile'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='students',
            field=models.ManyToManyField(related_name='cohorts_registered', to='apis.profile'),
        ),
    ]
