# Generated by Django 4.2.7 on 2024-07-15 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_cohort_instructors_alter_cohort_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.TimeField(default=datetime.time(1, 0), null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='meeting_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructors',
            field=models.ManyToManyField(related_name='courses_teaching', to='apis.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(related_name='courses_registered', through='apis.StudentSession', to='apis.profile'),
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.lessonnote'),
        ),
    ]
