# Generated by Django 4.2.7 on 2024-07-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0007_courseregistration_rename_img_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="instructors",
            field=models.ManyToManyField(
                related_name="sessions_teaching", to="apis.profile"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="students",
            field=models.ManyToManyField(
                related_name="sessions_registered",
                through="apis.StudentSession",
                to="apis.profile",
            ),
        ),
    ]
