# Generated by Django 4.2.7 on 2024-07-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0008_cohort_end_date_alter_session_instructors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="ispublic",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cohort",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
