# Generated by Django 4.2.7 on 2024-07-20 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0009_cohort_ispublic_cohort_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="classroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="apis.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.CharField(
                choices=[
                    ("PASS", "Pass"),
                    ("FAIL", "Fail"),
                    ("EXCELLENT", "Excellent"),
                    ("VERY GOOD", "Very Good"),
                    ("NOT GRADED", "Not Graded"),
                ],
                default="NOT GRADED",
                max_length=10,
            ),
        ),
    ]
