# Generated by Django 4.2.7 on 2024-07-20 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0010_alter_course_classroom_alter_submission_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="description",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="namespace",
        ),
        migrations.RemoveField(
            model_name="course",
            name="classroom",
        ),
        migrations.AddField(
            model_name="classroom",
            name="admins",
            field=models.ManyToManyField(
                related_name="classrooms_teaching", to="apis.profile"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="courses",
            field=models.ManyToManyField(to="apis.course"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                related_name="classrooms_registered", to="apis.profile"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                related_name="courses_teaching", to="apis.profile"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "STUDENT"),
                    ("INSTRUCTOR", "INSTRUCTOR"),
                    ("ADMIN", "ADMIN"),
                ],
                default="STUDENT",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="Cohort",
        ),
    ]
